# Generated by Django 4.2 on 2023-04-09 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Anonymous', max_length=200)),
                ('password', models.CharField(default='Anonymous', max_length=200)),
                ('avatar', models.ImageField(default='images/default_user.png', upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='photos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.user'),
        ),
    ]
