# Generated by Django 4.2 on 2023-04-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='comment_list',
            field=models.ManyToManyField(blank=True, to='polls.comment'),
        ),
    ]
