# Generated by Django 4.2 on 2023-04-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_photos_comment_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
