# Generated by Django 4.2 on 2023-04-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='photo_likes', to='polls.user'),
        ),
    ]
