# Generated by Django 4.2 on 2023-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_photos_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='likes',
        ),
        migrations.AddField(
            model_name='photos',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
